### ISSUE TITLE
Implement the pass through

### ISSUE THREAD

**Issue by glaslos** [mushorg/glutton#161]
Using TCP and UDP proxy or exclusion in the iptables rule spec (like port 22 for ssh)

**Comment by jerryyummy** [comment]
i would like to solve it. so there are something to do:
1. Proxy all TCP/UDP traffic 
2. Support multiple excluded ports 
3. Ensure Glutton can still capture malicious traffic
is it right?

**Comment by glaslos** [comment]
Pretty much, yes. I.e. we have this rule:
```
rules:
  - match: tcp dst port 23 or port 2323 or port 23231
    type: conn_handler
    target: telnet
```
this feature would support a rule like:
```
rules:
  - match: tcp dst port 22
    type: passthrough
```
